---
swagger: "2.0"
info:
  description: "This is a sample server."
  version: "1.0.0"
  title: "Swagger simple"
host: "localhost"
basePath: "/v2"
schemes:
- "http"
paths:
  /best_matches:
    post:
      summary: "Get sim images"
      description: ""
      operationId: "get_sim_images"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "vector"
        description: "Embedding of image"
        required: true
        schema:
          $ref: "#/definitions/Embedding"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "string"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Embedding:
    type: "object"
    properties:
      embedding:
        type: "array"
        items:
          type: "integer"
          format: "int64"
    example:
      embedding:
      - 0
      - 0
