# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Embedding(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, embedding: List[int]=None):  # noqa: E501
        """Embedding - a model defined in Swagger

        :param embedding: The embedding of this Embedding.  # noqa: E501
        :type embedding: List[int]
        """
        self.swagger_types = {
            'embedding': List[int]
        }

        self.attribute_map = {
            'embedding': 'embedding'
        }

        self._embedding = embedding

    @classmethod
    def from_dict(cls, dikt) -> 'Embedding':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Embedding of this Embedding.  # noqa: E501
        :rtype: Embedding
        """
        return util.deserialize_model(dikt, cls)

    @property
    def embedding(self) -> List[int]:
        """Gets the embedding of this Embedding.


        :return: The embedding of this Embedding.
        :rtype: List[int]
        """
        return self._embedding

    @embedding.setter
    def embedding(self, embedding: List[int]):
        """Sets the embedding of this Embedding.


        :param embedding: The embedding of this Embedding.
        :type embedding: List[int]
        """

        self._embedding = embedding
